// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: tiny-profile-service/v1/admin-person-service.proto

package tiny_profile_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminPersonService_Find_FullMethodName   = "/profile.service.AdminPersonService/Find"
	AdminPersonService_List_FullMethodName   = "/profile.service.AdminPersonService/List"
	AdminPersonService_Save_FullMethodName   = "/profile.service.AdminPersonService/Save"
	AdminPersonService_Delete_FullMethodName = "/profile.service.AdminPersonService/Delete"
	AdminPersonService_Remove_FullMethodName = "/profile.service.AdminPersonService/Remove"
)

// AdminPersonServiceClient is the client API for AdminPersonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminPersonServiceClient interface {
	Find(ctx context.Context, in *AdminPersonFindRequest, opts ...grpc.CallOption) (*AdminPersonInstanceResponse, error)
	List(ctx context.Context, in *AdminPersonListRequest, opts ...grpc.CallOption) (*AdminPersonInstancesResponse, error)
	Save(ctx context.Context, in *AdminPersonSaveRequest, opts ...grpc.CallOption) (*AdminPersonInstanceResponse, error)
	Delete(ctx context.Context, in *AdminPersonDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Remove(ctx context.Context, in *AdminPersonRemoveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type adminPersonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminPersonServiceClient(cc grpc.ClientConnInterface) AdminPersonServiceClient {
	return &adminPersonServiceClient{cc}
}

func (c *adminPersonServiceClient) Find(ctx context.Context, in *AdminPersonFindRequest, opts ...grpc.CallOption) (*AdminPersonInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminPersonInstanceResponse)
	err := c.cc.Invoke(ctx, AdminPersonService_Find_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminPersonServiceClient) List(ctx context.Context, in *AdminPersonListRequest, opts ...grpc.CallOption) (*AdminPersonInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminPersonInstancesResponse)
	err := c.cc.Invoke(ctx, AdminPersonService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminPersonServiceClient) Save(ctx context.Context, in *AdminPersonSaveRequest, opts ...grpc.CallOption) (*AdminPersonInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminPersonInstanceResponse)
	err := c.cc.Invoke(ctx, AdminPersonService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminPersonServiceClient) Delete(ctx context.Context, in *AdminPersonDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AdminPersonService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminPersonServiceClient) Remove(ctx context.Context, in *AdminPersonRemoveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AdminPersonService_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminPersonServiceServer is the server API for AdminPersonService service.
// All implementations must embed UnimplementedAdminPersonServiceServer
// for forward compatibility.
type AdminPersonServiceServer interface {
	Find(context.Context, *AdminPersonFindRequest) (*AdminPersonInstanceResponse, error)
	List(context.Context, *AdminPersonListRequest) (*AdminPersonInstancesResponse, error)
	Save(context.Context, *AdminPersonSaveRequest) (*AdminPersonInstanceResponse, error)
	Delete(context.Context, *AdminPersonDeleteRequest) (*emptypb.Empty, error)
	Remove(context.Context, *AdminPersonRemoveRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAdminPersonServiceServer()
}

// UnimplementedAdminPersonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminPersonServiceServer struct{}

func (UnimplementedAdminPersonServiceServer) Find(context.Context, *AdminPersonFindRequest) (*AdminPersonInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedAdminPersonServiceServer) List(context.Context, *AdminPersonListRequest) (*AdminPersonInstancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAdminPersonServiceServer) Save(context.Context, *AdminPersonSaveRequest) (*AdminPersonInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedAdminPersonServiceServer) Delete(context.Context, *AdminPersonDeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAdminPersonServiceServer) Remove(context.Context, *AdminPersonRemoveRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedAdminPersonServiceServer) mustEmbedUnimplementedAdminPersonServiceServer() {}
func (UnimplementedAdminPersonServiceServer) testEmbeddedByValue()                            {}

// UnsafeAdminPersonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminPersonServiceServer will
// result in compilation errors.
type UnsafeAdminPersonServiceServer interface {
	mustEmbedUnimplementedAdminPersonServiceServer()
}

func RegisterAdminPersonServiceServer(s grpc.ServiceRegistrar, srv AdminPersonServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminPersonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminPersonService_ServiceDesc, srv)
}

func _AdminPersonService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminPersonFindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminPersonServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminPersonService_Find_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminPersonServiceServer).Find(ctx, req.(*AdminPersonFindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminPersonService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminPersonListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminPersonServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminPersonService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminPersonServiceServer).List(ctx, req.(*AdminPersonListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminPersonService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminPersonSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminPersonServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminPersonService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminPersonServiceServer).Save(ctx, req.(*AdminPersonSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminPersonService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminPersonDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminPersonServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminPersonService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminPersonServiceServer).Delete(ctx, req.(*AdminPersonDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminPersonService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminPersonRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminPersonServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminPersonService_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminPersonServiceServer).Remove(ctx, req.(*AdminPersonRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminPersonService_ServiceDesc is the grpc.ServiceDesc for AdminPersonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminPersonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "profile.service.AdminPersonService",
	HandlerType: (*AdminPersonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Find",
			Handler:    _AdminPersonService_Find_Handler,
		},
		{
			MethodName: "List",
			Handler:    _AdminPersonService_List_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _AdminPersonService_Save_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AdminPersonService_Delete_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _AdminPersonService_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tiny-profile-service/v1/admin-person-service.proto",
}
