// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.0
// source: tiny-profile-service/v1/admin-person-service.proto

package tiny_profile_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminPersonFindRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminPersonFindRequest) Reset() {
	*x = AdminPersonFindRequest{}
	mi := &file_tiny_profile_service_v1_admin_person_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPersonFindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPersonFindRequest) ProtoMessage() {}

func (x *AdminPersonFindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_admin_person_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminPersonFindRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *AdminPersonFindRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *AdminPersonFindRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AdminPersonFindRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type AdminPersonFindRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 AdminPersonFindRequest_builder) Build() *AdminPersonFindRequest {
	m0 := &AdminPersonFindRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type AdminPersonListRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Offset      uint32                 `protobuf:"varint,1,opt,name=offset"`
	xxx_hidden_Limit       uint32                 `protobuf:"varint,2,opt,name=limit"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminPersonListRequest) Reset() {
	*x = AdminPersonListRequest{}
	mi := &file_tiny_profile_service_v1_admin_person_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPersonListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPersonListRequest) ProtoMessage() {}

func (x *AdminPersonListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_admin_person_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminPersonListRequest) GetOffset() uint32 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *AdminPersonListRequest) GetLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *AdminPersonListRequest) SetOffset(v uint32) {
	x.xxx_hidden_Offset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *AdminPersonListRequest) SetLimit(v uint32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *AdminPersonListRequest) HasOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AdminPersonListRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AdminPersonListRequest) ClearOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Offset = 0
}

func (x *AdminPersonListRequest) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Limit = 0
}

type AdminPersonListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Offset *uint32
	Limit  *uint32
}

func (b0 AdminPersonListRequest_builder) Build() *AdminPersonListRequest {
	m0 := &AdminPersonListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Offset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Offset = *b.Offset
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Limit = *b.Limit
	}
	return m0
}

type AdminPersonSaveRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance *Person                `protobuf:"bytes,1,opt,name=instance"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AdminPersonSaveRequest) Reset() {
	*x = AdminPersonSaveRequest{}
	mi := &file_tiny_profile_service_v1_admin_person_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPersonSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPersonSaveRequest) ProtoMessage() {}

func (x *AdminPersonSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_admin_person_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminPersonSaveRequest) GetInstance() *Person {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *AdminPersonSaveRequest) SetInstance(v *Person) {
	x.xxx_hidden_Instance = v
}

func (x *AdminPersonSaveRequest) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *AdminPersonSaveRequest) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

type AdminPersonSaveRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Instance *Person
}

func (b0 AdminPersonSaveRequest_builder) Build() *AdminPersonSaveRequest {
	m0 := &AdminPersonSaveRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	return m0
}

type AdminPersonDeleteRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminPersonDeleteRequest) Reset() {
	*x = AdminPersonDeleteRequest{}
	mi := &file_tiny_profile_service_v1_admin_person_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPersonDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPersonDeleteRequest) ProtoMessage() {}

func (x *AdminPersonDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_admin_person_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminPersonDeleteRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *AdminPersonDeleteRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *AdminPersonDeleteRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AdminPersonDeleteRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type AdminPersonDeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 AdminPersonDeleteRequest_builder) Build() *AdminPersonDeleteRequest {
	m0 := &AdminPersonDeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type AdminPersonRemoveRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminPersonRemoveRequest) Reset() {
	*x = AdminPersonRemoveRequest{}
	mi := &file_tiny_profile_service_v1_admin_person_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPersonRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPersonRemoveRequest) ProtoMessage() {}

func (x *AdminPersonRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_admin_person_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminPersonRemoveRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *AdminPersonRemoveRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *AdminPersonRemoveRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AdminPersonRemoveRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type AdminPersonRemoveRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 AdminPersonRemoveRequest_builder) Build() *AdminPersonRemoveRequest {
	m0 := &AdminPersonRemoveRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type AdminPersonInstanceResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance *Person                `protobuf:"bytes,1,opt,name=instance"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AdminPersonInstanceResponse) Reset() {
	*x = AdminPersonInstanceResponse{}
	mi := &file_tiny_profile_service_v1_admin_person_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPersonInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPersonInstanceResponse) ProtoMessage() {}

func (x *AdminPersonInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_admin_person_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminPersonInstanceResponse) GetInstance() *Person {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *AdminPersonInstanceResponse) SetInstance(v *Person) {
	x.xxx_hidden_Instance = v
}

func (x *AdminPersonInstanceResponse) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *AdminPersonInstanceResponse) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

type AdminPersonInstanceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Instance *Person
}

func (b0 AdminPersonInstanceResponse_builder) Build() *AdminPersonInstanceResponse {
	m0 := &AdminPersonInstanceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	return m0
}

type AdminPersonInstancesResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Offset      uint32                 `protobuf:"varint,1,opt,name=offset"`
	xxx_hidden_Limit       uint32                 `protobuf:"varint,2,opt,name=limit"`
	xxx_hidden_Instances   *[]*Person             `protobuf:"bytes,3,rep,name=instances"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminPersonInstancesResponse) Reset() {
	*x = AdminPersonInstancesResponse{}
	mi := &file_tiny_profile_service_v1_admin_person_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPersonInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPersonInstancesResponse) ProtoMessage() {}

func (x *AdminPersonInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_admin_person_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminPersonInstancesResponse) GetOffset() uint32 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *AdminPersonInstancesResponse) GetLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *AdminPersonInstancesResponse) GetInstances() []*Person {
	if x != nil {
		if x.xxx_hidden_Instances != nil {
			return *x.xxx_hidden_Instances
		}
	}
	return nil
}

func (x *AdminPersonInstancesResponse) SetOffset(v uint32) {
	x.xxx_hidden_Offset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *AdminPersonInstancesResponse) SetLimit(v uint32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *AdminPersonInstancesResponse) SetInstances(v []*Person) {
	x.xxx_hidden_Instances = &v
}

func (x *AdminPersonInstancesResponse) HasOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AdminPersonInstancesResponse) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AdminPersonInstancesResponse) ClearOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Offset = 0
}

func (x *AdminPersonInstancesResponse) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Limit = 0
}

type AdminPersonInstancesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Offset    *uint32
	Limit     *uint32
	Instances []*Person
}

func (b0 AdminPersonInstancesResponse_builder) Build() *AdminPersonInstancesResponse {
	m0 := &AdminPersonInstancesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Offset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Offset = *b.Offset
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Limit = *b.Limit
	}
	x.xxx_hidden_Instances = &b.Instances
	return m0
}

var File_tiny_profile_service_v1_admin_person_service_proto protoreflect.FileDescriptor

const file_tiny_profile_service_v1_admin_person_service_proto_rawDesc = "" +
	"\n" +
	"2tiny-profile-service/v1/admin-person-service.proto\x12\x0fprofile.service\x1a\x1bgoogle/protobuf/empty.proto\x1a&tiny-profile-service/v1/messages.proto\"(\n" +
	"\x16AdminPersonFindRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x16AdminPersonListRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"M\n" +
	"\x16AdminPersonSaveRequest\x123\n" +
	"\binstance\x18\x01 \x01(\v2\x17.profile.service.PersonR\binstance\"*\n" +
	"\x18AdminPersonDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"*\n" +
	"\x18AdminPersonRemoveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\x1bAdminPersonInstanceResponse\x123\n" +
	"\binstance\x18\x01 \x01(\v2\x17.profile.service.PersonR\binstance\"\x83\x01\n" +
	"\x1cAdminPersonInstancesResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x125\n" +
	"\tinstances\x18\x03 \x03(\v2\x17.profile.service.PersonR\tinstances2\xcc\x03\n" +
	"\x12AdminPersonService\x12]\n" +
	"\x04Find\x12'.profile.service.AdminPersonFindRequest\x1a,.profile.service.AdminPersonInstanceResponse\x12^\n" +
	"\x04List\x12'.profile.service.AdminPersonListRequest\x1a-.profile.service.AdminPersonInstancesResponse\x12]\n" +
	"\x04Save\x12'.profile.service.AdminPersonSaveRequest\x1a,.profile.service.AdminPersonInstanceResponse\x12K\n" +
	"\x06Delete\x12).profile.service.AdminPersonDeleteRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\x06Remove\x12).profile.service.AdminPersonRemoveRequest\x1a\x16.google.protobuf.EmptyB0Z.tiny-profile-service/grpc/tiny-profile-serviceb\beditionsp\xe8\a"

var file_tiny_profile_service_v1_admin_person_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tiny_profile_service_v1_admin_person_service_proto_goTypes = []any{
	(*AdminPersonFindRequest)(nil),       // 0: profile.service.AdminPersonFindRequest
	(*AdminPersonListRequest)(nil),       // 1: profile.service.AdminPersonListRequest
	(*AdminPersonSaveRequest)(nil),       // 2: profile.service.AdminPersonSaveRequest
	(*AdminPersonDeleteRequest)(nil),     // 3: profile.service.AdminPersonDeleteRequest
	(*AdminPersonRemoveRequest)(nil),     // 4: profile.service.AdminPersonRemoveRequest
	(*AdminPersonInstanceResponse)(nil),  // 5: profile.service.AdminPersonInstanceResponse
	(*AdminPersonInstancesResponse)(nil), // 6: profile.service.AdminPersonInstancesResponse
	(*Person)(nil),                       // 7: profile.service.Person
	(*emptypb.Empty)(nil),                // 8: google.protobuf.Empty
}
var file_tiny_profile_service_v1_admin_person_service_proto_depIdxs = []int32{
	7, // 0: profile.service.AdminPersonSaveRequest.instance:type_name -> profile.service.Person
	7, // 1: profile.service.AdminPersonInstanceResponse.instance:type_name -> profile.service.Person
	7, // 2: profile.service.AdminPersonInstancesResponse.instances:type_name -> profile.service.Person
	0, // 3: profile.service.AdminPersonService.Find:input_type -> profile.service.AdminPersonFindRequest
	1, // 4: profile.service.AdminPersonService.List:input_type -> profile.service.AdminPersonListRequest
	2, // 5: profile.service.AdminPersonService.Save:input_type -> profile.service.AdminPersonSaveRequest
	3, // 6: profile.service.AdminPersonService.Delete:input_type -> profile.service.AdminPersonDeleteRequest
	4, // 7: profile.service.AdminPersonService.Remove:input_type -> profile.service.AdminPersonRemoveRequest
	5, // 8: profile.service.AdminPersonService.Find:output_type -> profile.service.AdminPersonInstanceResponse
	6, // 9: profile.service.AdminPersonService.List:output_type -> profile.service.AdminPersonInstancesResponse
	5, // 10: profile.service.AdminPersonService.Save:output_type -> profile.service.AdminPersonInstanceResponse
	8, // 11: profile.service.AdminPersonService.Delete:output_type -> google.protobuf.Empty
	8, // 12: profile.service.AdminPersonService.Remove:output_type -> google.protobuf.Empty
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tiny_profile_service_v1_admin_person_service_proto_init() }
func file_tiny_profile_service_v1_admin_person_service_proto_init() {
	if File_tiny_profile_service_v1_admin_person_service_proto != nil {
		return
	}
	file_tiny_profile_service_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tiny_profile_service_v1_admin_person_service_proto_rawDesc), len(file_tiny_profile_service_v1_admin_person_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tiny_profile_service_v1_admin_person_service_proto_goTypes,
		DependencyIndexes: file_tiny_profile_service_v1_admin_person_service_proto_depIdxs,
		MessageInfos:      file_tiny_profile_service_v1_admin_person_service_proto_msgTypes,
	}.Build()
	File_tiny_profile_service_v1_admin_person_service_proto = out.File
	file_tiny_profile_service_v1_admin_person_service_proto_goTypes = nil
	file_tiny_profile_service_v1_admin_person_service_proto_depIdxs = nil
}
