// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.0
// source: tiny-profile-service/v1/admin-profile-service.proto

package tiny_profile_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminProfileFindRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminProfileFindRequest) Reset() {
	*x = AdminProfileFindRequest{}
	mi := &file_tiny_profile_service_v1_admin_profile_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminProfileFindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminProfileFindRequest) ProtoMessage() {}

func (x *AdminProfileFindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_admin_profile_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminProfileFindRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *AdminProfileFindRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *AdminProfileFindRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AdminProfileFindRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type AdminProfileFindRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 AdminProfileFindRequest_builder) Build() *AdminProfileFindRequest {
	m0 := &AdminProfileFindRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type AdminProfileListRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Offset      uint32                 `protobuf:"varint,1,opt,name=offset"`
	xxx_hidden_Limit       uint32                 `protobuf:"varint,2,opt,name=limit"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminProfileListRequest) Reset() {
	*x = AdminProfileListRequest{}
	mi := &file_tiny_profile_service_v1_admin_profile_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminProfileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminProfileListRequest) ProtoMessage() {}

func (x *AdminProfileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_admin_profile_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminProfileListRequest) GetOffset() uint32 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *AdminProfileListRequest) GetLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *AdminProfileListRequest) SetOffset(v uint32) {
	x.xxx_hidden_Offset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *AdminProfileListRequest) SetLimit(v uint32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *AdminProfileListRequest) HasOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AdminProfileListRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AdminProfileListRequest) ClearOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Offset = 0
}

func (x *AdminProfileListRequest) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Limit = 0
}

type AdminProfileListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Offset *uint32
	Limit  *uint32
}

func (b0 AdminProfileListRequest_builder) Build() *AdminProfileListRequest {
	m0 := &AdminProfileListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Offset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Offset = *b.Offset
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Limit = *b.Limit
	}
	return m0
}

type AdminProfileSaveRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PersonId    *string                `protobuf:"bytes,1,opt,name=person_id,json=personId"`
	xxx_hidden_Instance    *Profile               `protobuf:"bytes,2,opt,name=instance"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminProfileSaveRequest) Reset() {
	*x = AdminProfileSaveRequest{}
	mi := &file_tiny_profile_service_v1_admin_profile_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminProfileSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminProfileSaveRequest) ProtoMessage() {}

func (x *AdminProfileSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_admin_profile_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminProfileSaveRequest) GetPersonId() string {
	if x != nil {
		if x.xxx_hidden_PersonId != nil {
			return *x.xxx_hidden_PersonId
		}
		return ""
	}
	return ""
}

func (x *AdminProfileSaveRequest) GetInstance() *Profile {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *AdminProfileSaveRequest) SetPersonId(v string) {
	x.xxx_hidden_PersonId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *AdminProfileSaveRequest) SetInstance(v *Profile) {
	x.xxx_hidden_Instance = v
}

func (x *AdminProfileSaveRequest) HasPersonId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AdminProfileSaveRequest) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *AdminProfileSaveRequest) ClearPersonId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PersonId = nil
}

func (x *AdminProfileSaveRequest) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

type AdminProfileSaveRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PersonId *string
	Instance *Profile
}

func (b0 AdminProfileSaveRequest_builder) Build() *AdminProfileSaveRequest {
	m0 := &AdminProfileSaveRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PersonId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_PersonId = b.PersonId
	}
	x.xxx_hidden_Instance = b.Instance
	return m0
}

type AdminProfileDeleteRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminProfileDeleteRequest) Reset() {
	*x = AdminProfileDeleteRequest{}
	mi := &file_tiny_profile_service_v1_admin_profile_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminProfileDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminProfileDeleteRequest) ProtoMessage() {}

func (x *AdminProfileDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_admin_profile_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminProfileDeleteRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *AdminProfileDeleteRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *AdminProfileDeleteRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AdminProfileDeleteRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type AdminProfileDeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 AdminProfileDeleteRequest_builder) Build() *AdminProfileDeleteRequest {
	m0 := &AdminProfileDeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type AdminProfileRemoveRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminProfileRemoveRequest) Reset() {
	*x = AdminProfileRemoveRequest{}
	mi := &file_tiny_profile_service_v1_admin_profile_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminProfileRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminProfileRemoveRequest) ProtoMessage() {}

func (x *AdminProfileRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_admin_profile_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminProfileRemoveRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *AdminProfileRemoveRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *AdminProfileRemoveRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AdminProfileRemoveRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type AdminProfileRemoveRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 AdminProfileRemoveRequest_builder) Build() *AdminProfileRemoveRequest {
	m0 := &AdminProfileRemoveRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type AdminProfileInstanceResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance *Profile               `protobuf:"bytes,1,opt,name=instance"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AdminProfileInstanceResponse) Reset() {
	*x = AdminProfileInstanceResponse{}
	mi := &file_tiny_profile_service_v1_admin_profile_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminProfileInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminProfileInstanceResponse) ProtoMessage() {}

func (x *AdminProfileInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_admin_profile_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminProfileInstanceResponse) GetInstance() *Profile {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *AdminProfileInstanceResponse) SetInstance(v *Profile) {
	x.xxx_hidden_Instance = v
}

func (x *AdminProfileInstanceResponse) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *AdminProfileInstanceResponse) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

type AdminProfileInstanceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Instance *Profile
}

func (b0 AdminProfileInstanceResponse_builder) Build() *AdminProfileInstanceResponse {
	m0 := &AdminProfileInstanceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	return m0
}

type AdminProfileInstancesResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Offset      uint32                 `protobuf:"varint,1,opt,name=offset"`
	xxx_hidden_Limit       uint32                 `protobuf:"varint,2,opt,name=limit"`
	xxx_hidden_Instances   *[]*Profile            `protobuf:"bytes,3,rep,name=instances"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminProfileInstancesResponse) Reset() {
	*x = AdminProfileInstancesResponse{}
	mi := &file_tiny_profile_service_v1_admin_profile_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminProfileInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminProfileInstancesResponse) ProtoMessage() {}

func (x *AdminProfileInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_admin_profile_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminProfileInstancesResponse) GetOffset() uint32 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *AdminProfileInstancesResponse) GetLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *AdminProfileInstancesResponse) GetInstances() []*Profile {
	if x != nil {
		if x.xxx_hidden_Instances != nil {
			return *x.xxx_hidden_Instances
		}
	}
	return nil
}

func (x *AdminProfileInstancesResponse) SetOffset(v uint32) {
	x.xxx_hidden_Offset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *AdminProfileInstancesResponse) SetLimit(v uint32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *AdminProfileInstancesResponse) SetInstances(v []*Profile) {
	x.xxx_hidden_Instances = &v
}

func (x *AdminProfileInstancesResponse) HasOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AdminProfileInstancesResponse) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AdminProfileInstancesResponse) ClearOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Offset = 0
}

func (x *AdminProfileInstancesResponse) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Limit = 0
}

type AdminProfileInstancesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Offset    *uint32
	Limit     *uint32
	Instances []*Profile
}

func (b0 AdminProfileInstancesResponse_builder) Build() *AdminProfileInstancesResponse {
	m0 := &AdminProfileInstancesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Offset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Offset = *b.Offset
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Limit = *b.Limit
	}
	x.xxx_hidden_Instances = &b.Instances
	return m0
}

type AdminProfileInstancesByPerson struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PersonId    *string                `protobuf:"bytes,1,opt,name=person_id,json=personId"`
	xxx_hidden_Instances   *[]*Profile            `protobuf:"bytes,2,rep,name=instances"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminProfileInstancesByPerson) Reset() {
	*x = AdminProfileInstancesByPerson{}
	mi := &file_tiny_profile_service_v1_admin_profile_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminProfileInstancesByPerson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminProfileInstancesByPerson) ProtoMessage() {}

func (x *AdminProfileInstancesByPerson) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_admin_profile_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminProfileInstancesByPerson) GetPersonId() string {
	if x != nil {
		if x.xxx_hidden_PersonId != nil {
			return *x.xxx_hidden_PersonId
		}
		return ""
	}
	return ""
}

func (x *AdminProfileInstancesByPerson) GetInstances() []*Profile {
	if x != nil {
		if x.xxx_hidden_Instances != nil {
			return *x.xxx_hidden_Instances
		}
	}
	return nil
}

func (x *AdminProfileInstancesByPerson) SetPersonId(v string) {
	x.xxx_hidden_PersonId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *AdminProfileInstancesByPerson) SetInstances(v []*Profile) {
	x.xxx_hidden_Instances = &v
}

func (x *AdminProfileInstancesByPerson) HasPersonId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AdminProfileInstancesByPerson) ClearPersonId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PersonId = nil
}

type AdminProfileInstancesByPerson_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PersonId  *string
	Instances []*Profile
}

func (b0 AdminProfileInstancesByPerson_builder) Build() *AdminProfileInstancesByPerson {
	m0 := &AdminProfileInstancesByPerson{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PersonId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_PersonId = b.PersonId
	}
	x.xxx_hidden_Instances = &b.Instances
	return m0
}

type AdminProfileInstancesByPersonsResponse struct {
	state                  protoimpl.MessageState            `protogen:"opaque.v1"`
	xxx_hidden_Offset      uint32                            `protobuf:"varint,1,opt,name=offset"`
	xxx_hidden_Limit       uint32                            `protobuf:"varint,2,opt,name=limit"`
	xxx_hidden_Instances   *[]*AdminProfileInstancesByPerson `protobuf:"bytes,3,rep,name=instances"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminProfileInstancesByPersonsResponse) Reset() {
	*x = AdminProfileInstancesByPersonsResponse{}
	mi := &file_tiny_profile_service_v1_admin_profile_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminProfileInstancesByPersonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminProfileInstancesByPersonsResponse) ProtoMessage() {}

func (x *AdminProfileInstancesByPersonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_admin_profile_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AdminProfileInstancesByPersonsResponse) GetOffset() uint32 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *AdminProfileInstancesByPersonsResponse) GetLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *AdminProfileInstancesByPersonsResponse) GetInstances() []*AdminProfileInstancesByPerson {
	if x != nil {
		if x.xxx_hidden_Instances != nil {
			return *x.xxx_hidden_Instances
		}
	}
	return nil
}

func (x *AdminProfileInstancesByPersonsResponse) SetOffset(v uint32) {
	x.xxx_hidden_Offset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *AdminProfileInstancesByPersonsResponse) SetLimit(v uint32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *AdminProfileInstancesByPersonsResponse) SetInstances(v []*AdminProfileInstancesByPerson) {
	x.xxx_hidden_Instances = &v
}

func (x *AdminProfileInstancesByPersonsResponse) HasOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *AdminProfileInstancesByPersonsResponse) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AdminProfileInstancesByPersonsResponse) ClearOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Offset = 0
}

func (x *AdminProfileInstancesByPersonsResponse) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Limit = 0
}

type AdminProfileInstancesByPersonsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Offset    *uint32
	Limit     *uint32
	Instances []*AdminProfileInstancesByPerson
}

func (b0 AdminProfileInstancesByPersonsResponse_builder) Build() *AdminProfileInstancesByPersonsResponse {
	m0 := &AdminProfileInstancesByPersonsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Offset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Offset = *b.Offset
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Limit = *b.Limit
	}
	x.xxx_hidden_Instances = &b.Instances
	return m0
}

var File_tiny_profile_service_v1_admin_profile_service_proto protoreflect.FileDescriptor

const file_tiny_profile_service_v1_admin_profile_service_proto_rawDesc = "" +
	"\n" +
	"3tiny-profile-service/v1/admin-profile-service.proto\x12\x0fprofile.service\x1a\x1bgoogle/protobuf/empty.proto\x1a&tiny-profile-service/v1/messages.proto\")\n" +
	"\x17AdminProfileFindRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x17AdminProfileListRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"l\n" +
	"\x17AdminProfileSaveRequest\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\x124\n" +
	"\binstance\x18\x02 \x01(\v2\x18.profile.service.ProfileR\binstance\"+\n" +
	"\x19AdminProfileDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x19AdminProfileRemoveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"T\n" +
	"\x1cAdminProfileInstanceResponse\x124\n" +
	"\binstance\x18\x01 \x01(\v2\x18.profile.service.ProfileR\binstance\"\x85\x01\n" +
	"\x1dAdminProfileInstancesResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x126\n" +
	"\tinstances\x18\x03 \x03(\v2\x18.profile.service.ProfileR\tinstances\"t\n" +
	"\x1dAdminProfileInstancesByPerson\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\x126\n" +
	"\tinstances\x18\x02 \x03(\v2\x18.profile.service.ProfileR\tinstances\"\xa4\x01\n" +
	"&AdminProfileInstancesByPersonsResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12L\n" +
	"\tinstances\x18\x03 \x03(\v2..profile.service.AdminProfileInstancesByPersonR\tinstances2\xde\x03\n" +
	"\x13AdminProfileService\x12_\n" +
	"\x04Find\x12(.profile.service.AdminProfileFindRequest\x1a-.profile.service.AdminProfileInstanceResponse\x12i\n" +
	"\x04List\x12(.profile.service.AdminProfileListRequest\x1a7.profile.service.AdminProfileInstancesByPersonsResponse\x12_\n" +
	"\x04Save\x12(.profile.service.AdminProfileSaveRequest\x1a-.profile.service.AdminProfileInstanceResponse\x12L\n" +
	"\x06Delete\x12*.profile.service.AdminProfileDeleteRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\x06Remove\x12*.profile.service.AdminProfileRemoveRequest\x1a\x16.google.protobuf.EmptyB0Z.tiny-profile-service/grpc/tiny-profile-serviceb\beditionsp\xe8\a"

var file_tiny_profile_service_v1_admin_profile_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_tiny_profile_service_v1_admin_profile_service_proto_goTypes = []any{
	(*AdminProfileFindRequest)(nil),                // 0: profile.service.AdminProfileFindRequest
	(*AdminProfileListRequest)(nil),                // 1: profile.service.AdminProfileListRequest
	(*AdminProfileSaveRequest)(nil),                // 2: profile.service.AdminProfileSaveRequest
	(*AdminProfileDeleteRequest)(nil),              // 3: profile.service.AdminProfileDeleteRequest
	(*AdminProfileRemoveRequest)(nil),              // 4: profile.service.AdminProfileRemoveRequest
	(*AdminProfileInstanceResponse)(nil),           // 5: profile.service.AdminProfileInstanceResponse
	(*AdminProfileInstancesResponse)(nil),          // 6: profile.service.AdminProfileInstancesResponse
	(*AdminProfileInstancesByPerson)(nil),          // 7: profile.service.AdminProfileInstancesByPerson
	(*AdminProfileInstancesByPersonsResponse)(nil), // 8: profile.service.AdminProfileInstancesByPersonsResponse
	(*Profile)(nil),                                // 9: profile.service.Profile
	(*emptypb.Empty)(nil),                          // 10: google.protobuf.Empty
}
var file_tiny_profile_service_v1_admin_profile_service_proto_depIdxs = []int32{
	9,  // 0: profile.service.AdminProfileSaveRequest.instance:type_name -> profile.service.Profile
	9,  // 1: profile.service.AdminProfileInstanceResponse.instance:type_name -> profile.service.Profile
	9,  // 2: profile.service.AdminProfileInstancesResponse.instances:type_name -> profile.service.Profile
	9,  // 3: profile.service.AdminProfileInstancesByPerson.instances:type_name -> profile.service.Profile
	7,  // 4: profile.service.AdminProfileInstancesByPersonsResponse.instances:type_name -> profile.service.AdminProfileInstancesByPerson
	0,  // 5: profile.service.AdminProfileService.Find:input_type -> profile.service.AdminProfileFindRequest
	1,  // 6: profile.service.AdminProfileService.List:input_type -> profile.service.AdminProfileListRequest
	2,  // 7: profile.service.AdminProfileService.Save:input_type -> profile.service.AdminProfileSaveRequest
	3,  // 8: profile.service.AdminProfileService.Delete:input_type -> profile.service.AdminProfileDeleteRequest
	4,  // 9: profile.service.AdminProfileService.Remove:input_type -> profile.service.AdminProfileRemoveRequest
	5,  // 10: profile.service.AdminProfileService.Find:output_type -> profile.service.AdminProfileInstanceResponse
	8,  // 11: profile.service.AdminProfileService.List:output_type -> profile.service.AdminProfileInstancesByPersonsResponse
	5,  // 12: profile.service.AdminProfileService.Save:output_type -> profile.service.AdminProfileInstanceResponse
	10, // 13: profile.service.AdminProfileService.Delete:output_type -> google.protobuf.Empty
	10, // 14: profile.service.AdminProfileService.Remove:output_type -> google.protobuf.Empty
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_tiny_profile_service_v1_admin_profile_service_proto_init() }
func file_tiny_profile_service_v1_admin_profile_service_proto_init() {
	if File_tiny_profile_service_v1_admin_profile_service_proto != nil {
		return
	}
	file_tiny_profile_service_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tiny_profile_service_v1_admin_profile_service_proto_rawDesc), len(file_tiny_profile_service_v1_admin_profile_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tiny_profile_service_v1_admin_profile_service_proto_goTypes,
		DependencyIndexes: file_tiny_profile_service_v1_admin_profile_service_proto_depIdxs,
		MessageInfos:      file_tiny_profile_service_v1_admin_profile_service_proto_msgTypes,
	}.Build()
	File_tiny_profile_service_v1_admin_profile_service_proto = out.File
	file_tiny_profile_service_v1_admin_profile_service_proto_goTypes = nil
	file_tiny_profile_service_v1_admin_profile_service_proto_depIdxs = nil
}
