// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: tiny-profile-service/v1/admin-profile-service.proto

package tiny_profile_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminProfileService_Find_FullMethodName   = "/profile.service.AdminProfileService/Find"
	AdminProfileService_List_FullMethodName   = "/profile.service.AdminProfileService/List"
	AdminProfileService_Save_FullMethodName   = "/profile.service.AdminProfileService/Save"
	AdminProfileService_Delete_FullMethodName = "/profile.service.AdminProfileService/Delete"
	AdminProfileService_Remove_FullMethodName = "/profile.service.AdminProfileService/Remove"
)

// AdminProfileServiceClient is the client API for AdminProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminProfileServiceClient interface {
	Find(ctx context.Context, in *AdminProfileFindRequest, opts ...grpc.CallOption) (*AdminProfileInstanceResponse, error)
	List(ctx context.Context, in *AdminProfileListRequest, opts ...grpc.CallOption) (*AdminProfileInstancesByPersonsResponse, error)
	Save(ctx context.Context, in *AdminProfileSaveRequest, opts ...grpc.CallOption) (*AdminProfileInstanceResponse, error)
	Delete(ctx context.Context, in *AdminProfileDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Remove(ctx context.Context, in *AdminProfileRemoveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type adminProfileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminProfileServiceClient(cc grpc.ClientConnInterface) AdminProfileServiceClient {
	return &adminProfileServiceClient{cc}
}

func (c *adminProfileServiceClient) Find(ctx context.Context, in *AdminProfileFindRequest, opts ...grpc.CallOption) (*AdminProfileInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminProfileInstanceResponse)
	err := c.cc.Invoke(ctx, AdminProfileService_Find_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminProfileServiceClient) List(ctx context.Context, in *AdminProfileListRequest, opts ...grpc.CallOption) (*AdminProfileInstancesByPersonsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminProfileInstancesByPersonsResponse)
	err := c.cc.Invoke(ctx, AdminProfileService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminProfileServiceClient) Save(ctx context.Context, in *AdminProfileSaveRequest, opts ...grpc.CallOption) (*AdminProfileInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminProfileInstanceResponse)
	err := c.cc.Invoke(ctx, AdminProfileService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminProfileServiceClient) Delete(ctx context.Context, in *AdminProfileDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AdminProfileService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminProfileServiceClient) Remove(ctx context.Context, in *AdminProfileRemoveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AdminProfileService_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminProfileServiceServer is the server API for AdminProfileService service.
// All implementations must embed UnimplementedAdminProfileServiceServer
// for forward compatibility.
type AdminProfileServiceServer interface {
	Find(context.Context, *AdminProfileFindRequest) (*AdminProfileInstanceResponse, error)
	List(context.Context, *AdminProfileListRequest) (*AdminProfileInstancesByPersonsResponse, error)
	Save(context.Context, *AdminProfileSaveRequest) (*AdminProfileInstanceResponse, error)
	Delete(context.Context, *AdminProfileDeleteRequest) (*emptypb.Empty, error)
	Remove(context.Context, *AdminProfileRemoveRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAdminProfileServiceServer()
}

// UnimplementedAdminProfileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminProfileServiceServer struct{}

func (UnimplementedAdminProfileServiceServer) Find(context.Context, *AdminProfileFindRequest) (*AdminProfileInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedAdminProfileServiceServer) List(context.Context, *AdminProfileListRequest) (*AdminProfileInstancesByPersonsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAdminProfileServiceServer) Save(context.Context, *AdminProfileSaveRequest) (*AdminProfileInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedAdminProfileServiceServer) Delete(context.Context, *AdminProfileDeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAdminProfileServiceServer) Remove(context.Context, *AdminProfileRemoveRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedAdminProfileServiceServer) mustEmbedUnimplementedAdminProfileServiceServer() {}
func (UnimplementedAdminProfileServiceServer) testEmbeddedByValue()                             {}

// UnsafeAdminProfileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminProfileServiceServer will
// result in compilation errors.
type UnsafeAdminProfileServiceServer interface {
	mustEmbedUnimplementedAdminProfileServiceServer()
}

func RegisterAdminProfileServiceServer(s grpc.ServiceRegistrar, srv AdminProfileServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminProfileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminProfileService_ServiceDesc, srv)
}

func _AdminProfileService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminProfileFindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProfileServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProfileService_Find_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProfileServiceServer).Find(ctx, req.(*AdminProfileFindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminProfileService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminProfileListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProfileServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProfileService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProfileServiceServer).List(ctx, req.(*AdminProfileListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminProfileService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminProfileSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProfileServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProfileService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProfileServiceServer).Save(ctx, req.(*AdminProfileSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminProfileService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminProfileDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProfileServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProfileService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProfileServiceServer).Delete(ctx, req.(*AdminProfileDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminProfileService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminProfileRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminProfileServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminProfileService_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminProfileServiceServer).Remove(ctx, req.(*AdminProfileRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminProfileService_ServiceDesc is the grpc.ServiceDesc for AdminProfileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminProfileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "profile.service.AdminProfileService",
	HandlerType: (*AdminProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Find",
			Handler:    _AdminProfileService_Find_Handler,
		},
		{
			MethodName: "List",
			Handler:    _AdminProfileService_List_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _AdminProfileService_Save_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AdminProfileService_Delete_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _AdminProfileService_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tiny-profile-service/v1/admin-profile-service.proto",
}
