// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.0
// source: tiny-profile-service/v1/messages.proto

package tiny_profile_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Profile содержит региональные настройки и метаданные пользователя.
// Этот объект используется для локализации интерфейса и отправки пушей с учетом таймзоны.
type Profile struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_UserId      *string                `protobuf:"bytes,2,opt,name=user_id,json=userId"`
	xxx_hidden_TimeZone    *string                `protobuf:"bytes,3,opt,name=time_zone,json=timeZone"`
	xxx_hidden_Lang        *string                `protobuf:"bytes,4,opt,name=lang"`
	xxx_hidden_Active      bool                   `protobuf:"varint,5,opt,name=active"`
	xxx_hidden_Deleted     bool                   `protobuf:"varint,6,opt,name=deleted"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt"`
	xxx_hidden_UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_tiny_profile_service_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Profile) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Profile) GetUserId() string {
	if x != nil {
		if x.xxx_hidden_UserId != nil {
			return *x.xxx_hidden_UserId
		}
		return ""
	}
	return ""
}

func (x *Profile) GetTimeZone() string {
	if x != nil {
		if x.xxx_hidden_TimeZone != nil {
			return *x.xxx_hidden_TimeZone
		}
		return ""
	}
	return ""
}

func (x *Profile) GetLang() string {
	if x != nil {
		if x.xxx_hidden_Lang != nil {
			return *x.xxx_hidden_Lang
		}
		return ""
	}
	return ""
}

func (x *Profile) GetActive() bool {
	if x != nil {
		return x.xxx_hidden_Active
	}
	return false
}

func (x *Profile) GetDeleted() bool {
	if x != nil {
		return x.xxx_hidden_Deleted
	}
	return false
}

func (x *Profile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Profile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *Profile) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *Profile) SetUserId(v string) {
	x.xxx_hidden_UserId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *Profile) SetTimeZone(v string) {
	x.xxx_hidden_TimeZone = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *Profile) SetLang(v string) {
	x.xxx_hidden_Lang = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *Profile) SetActive(v bool) {
	x.xxx_hidden_Active = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *Profile) SetDeleted(v bool) {
	x.xxx_hidden_Deleted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *Profile) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Profile) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *Profile) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Profile) HasUserId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Profile) HasTimeZone() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Profile) HasLang() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Profile) HasActive() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Profile) HasDeleted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Profile) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Profile) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *Profile) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Profile) ClearUserId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_UserId = nil
}

func (x *Profile) ClearTimeZone() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_TimeZone = nil
}

func (x *Profile) ClearLang() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Lang = nil
}

func (x *Profile) ClearActive() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Active = false
}

func (x *Profile) ClearDeleted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Deleted = false
}

func (x *Profile) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *Profile) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type Profile_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Уникальный идентификатор профиля (UUIDv7).
	Id *string
	// Идентификатор владельца профиля из сервиса авторизации.
	UserId *string
	// Часовой пояс пользователя в формате IANA (например, "Europe/Moscow").
	TimeZone *string
	// Двухбуквенный код языка в формате ISO 639-1 (например, "ru", "en").
	Lang *string
	// Флаг активности аккаунта. Если false, пользователь временно заблокирован.
	Active *bool
	// Флаг "мягкого" удаления. Истинен, если профиль удалён
	Deleted *bool
	// Время создания профиля в системе.
	CreatedAt *timestamppb.Timestamp
	// Время последнего изменения любых данных профиля.
	UpdatedAt *timestamppb.Timestamp
}

func (b0 Profile_builder) Build() *Profile {
	m0 := &Profile{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Id = b.Id
	}
	if b.UserId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_UserId = b.UserId
	}
	if b.TimeZone != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_TimeZone = b.TimeZone
	}
	if b.Lang != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_Lang = b.Lang
	}
	if b.Active != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Active = *b.Active
	}
	if b.Deleted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_Deleted = *b.Deleted
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

// Person представляет сотрудника компании со всеми персональными
// данными, рабочим статусом и привязанными профилями.
type Person struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_ExternalId  *string                `protobuf:"bytes,2,opt,name=external_id,json=externalId"`
	xxx_hidden_LastName    *string                `protobuf:"bytes,3,opt,name=last_name,json=lastName"`
	xxx_hidden_FirstName   *string                `protobuf:"bytes,4,opt,name=first_name,json=firstName"`
	xxx_hidden_Patronymic  *string                `protobuf:"bytes,5,opt,name=patronymic"`
	xxx_hidden_BirthDay    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=birth_day,json=birthDay"`
	xxx_hidden_Department  *string                `protobuf:"bytes,7,opt,name=department"`
	xxx_hidden_Position    *string                `protobuf:"bytes,8,opt,name=position"`
	xxx_hidden_Status      *string                `protobuf:"bytes,9,opt,name=status"`
	xxx_hidden_AvatarUrl   *string                `protobuf:"bytes,10,opt,name=avatar_url,json=avatarUrl"`
	xxx_hidden_Active      bool                   `protobuf:"varint,11,opt,name=active"`
	xxx_hidden_Deleted     bool                   `protobuf:"varint,12,opt,name=deleted"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt"`
	xxx_hidden_UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt"`
	xxx_hidden_Profiles    *[]*Profile            `protobuf:"bytes,15,rep,name=profiles"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_tiny_profile_service_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Person) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Person) GetExternalId() string {
	if x != nil {
		if x.xxx_hidden_ExternalId != nil {
			return *x.xxx_hidden_ExternalId
		}
		return ""
	}
	return ""
}

func (x *Person) GetLastName() string {
	if x != nil {
		if x.xxx_hidden_LastName != nil {
			return *x.xxx_hidden_LastName
		}
		return ""
	}
	return ""
}

func (x *Person) GetFirstName() string {
	if x != nil {
		if x.xxx_hidden_FirstName != nil {
			return *x.xxx_hidden_FirstName
		}
		return ""
	}
	return ""
}

func (x *Person) GetPatronymic() string {
	if x != nil {
		if x.xxx_hidden_Patronymic != nil {
			return *x.xxx_hidden_Patronymic
		}
		return ""
	}
	return ""
}

func (x *Person) GetBirthDay() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_BirthDay
	}
	return nil
}

func (x *Person) GetDepartment() string {
	if x != nil {
		if x.xxx_hidden_Department != nil {
			return *x.xxx_hidden_Department
		}
		return ""
	}
	return ""
}

func (x *Person) GetPosition() string {
	if x != nil {
		if x.xxx_hidden_Position != nil {
			return *x.xxx_hidden_Position
		}
		return ""
	}
	return ""
}

func (x *Person) GetStatus() string {
	if x != nil {
		if x.xxx_hidden_Status != nil {
			return *x.xxx_hidden_Status
		}
		return ""
	}
	return ""
}

func (x *Person) GetAvatarUrl() string {
	if x != nil {
		if x.xxx_hidden_AvatarUrl != nil {
			return *x.xxx_hidden_AvatarUrl
		}
		return ""
	}
	return ""
}

func (x *Person) GetActive() bool {
	if x != nil {
		return x.xxx_hidden_Active
	}
	return false
}

func (x *Person) GetDeleted() bool {
	if x != nil {
		return x.xxx_hidden_Deleted
	}
	return false
}

func (x *Person) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Person) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *Person) GetProfiles() []*Profile {
	if x != nil {
		if x.xxx_hidden_Profiles != nil {
			return *x.xxx_hidden_Profiles
		}
	}
	return nil
}

func (x *Person) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 15)
}

func (x *Person) SetExternalId(v string) {
	x.xxx_hidden_ExternalId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 15)
}

func (x *Person) SetLastName(v string) {
	x.xxx_hidden_LastName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 15)
}

func (x *Person) SetFirstName(v string) {
	x.xxx_hidden_FirstName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 15)
}

func (x *Person) SetPatronymic(v string) {
	x.xxx_hidden_Patronymic = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 15)
}

func (x *Person) SetBirthDay(v *timestamppb.Timestamp) {
	x.xxx_hidden_BirthDay = v
}

func (x *Person) SetDepartment(v string) {
	x.xxx_hidden_Department = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 15)
}

func (x *Person) SetPosition(v string) {
	x.xxx_hidden_Position = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 15)
}

func (x *Person) SetStatus(v string) {
	x.xxx_hidden_Status = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 15)
}

func (x *Person) SetAvatarUrl(v string) {
	x.xxx_hidden_AvatarUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 15)
}

func (x *Person) SetActive(v bool) {
	x.xxx_hidden_Active = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 15)
}

func (x *Person) SetDeleted(v bool) {
	x.xxx_hidden_Deleted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 15)
}

func (x *Person) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Person) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *Person) SetProfiles(v []*Profile) {
	x.xxx_hidden_Profiles = &v
}

func (x *Person) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Person) HasExternalId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Person) HasLastName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Person) HasFirstName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Person) HasPatronymic() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Person) HasBirthDay() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BirthDay != nil
}

func (x *Person) HasDepartment() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Person) HasPosition() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *Person) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *Person) HasAvatarUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *Person) HasActive() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *Person) HasDeleted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *Person) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Person) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *Person) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Person) ClearExternalId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ExternalId = nil
}

func (x *Person) ClearLastName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_LastName = nil
}

func (x *Person) ClearFirstName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_FirstName = nil
}

func (x *Person) ClearPatronymic() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Patronymic = nil
}

func (x *Person) ClearBirthDay() {
	x.xxx_hidden_BirthDay = nil
}

func (x *Person) ClearDepartment() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Department = nil
}

func (x *Person) ClearPosition() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Position = nil
}

func (x *Person) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Status = nil
}

func (x *Person) ClearAvatarUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_AvatarUrl = nil
}

func (x *Person) ClearActive() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_Active = false
}

func (x *Person) ClearDeleted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_Deleted = false
}

func (x *Person) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *Person) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type Person_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Id — уникальный идентификатор профиля (UUIDv7).
	Id *string
	// ExternalId — уникальный идентификатор сотрудника из внешней системы.
	ExternalId *string
	// LastName — фамилия сотрудника.
	LastName *string
	// FirstName — имя сотрудника.
	FirstName *string
	// Patronymic — отчество сотрудника.
	Patronymic *string
	// BirthDay — дата рождения сотрудника (время сбрасывается в 00:00:00 UTC).
	BirthDay *timestamppb.Timestamp
	// Department — департамент или отдел, к которому привязан сотрудник.
	Department *string
	// Position — текущая должность сотрудника.
	Position *string
	// Status — рабочий статус (например, "active", "on_vacation", "fired").
	Status *string
	// AvatarUrl — прямая ссылка на аватар или фотографию сотрудника.
	AvatarUrl *string
	// Active — флаг активности аккаунта. Если false, пользователь временно заблокирован.
	Active *bool
	// Deleted — флаг "мягкого" удаления. Истинен, если сотрудник удалён.
	Deleted *bool
	// CreatedAt — время создания профиля в системе.
	CreatedAt *timestamppb.Timestamp
	// UpdatedAt — время последнего изменения любых данных профиля.
	UpdatedAt *timestamppb.Timestamp
	// Profiles — список связанных профилей сотрудника во внешних сервисах.
	Profiles []*Profile
}

func (b0 Person_builder) Build() *Person {
	m0 := &Person{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 15)
		x.xxx_hidden_Id = b.Id
	}
	if b.ExternalId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 15)
		x.xxx_hidden_ExternalId = b.ExternalId
	}
	if b.LastName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 15)
		x.xxx_hidden_LastName = b.LastName
	}
	if b.FirstName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 15)
		x.xxx_hidden_FirstName = b.FirstName
	}
	if b.Patronymic != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 15)
		x.xxx_hidden_Patronymic = b.Patronymic
	}
	x.xxx_hidden_BirthDay = b.BirthDay
	if b.Department != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 15)
		x.xxx_hidden_Department = b.Department
	}
	if b.Position != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 15)
		x.xxx_hidden_Position = b.Position
	}
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 15)
		x.xxx_hidden_Status = b.Status
	}
	if b.AvatarUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 15)
		x.xxx_hidden_AvatarUrl = b.AvatarUrl
	}
	if b.Active != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 15)
		x.xxx_hidden_Active = *b.Active
	}
	if b.Deleted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 15)
		x.xxx_hidden_Deleted = *b.Deleted
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	x.xxx_hidden_Profiles = &b.Profiles
	return m0
}

var File_tiny_profile_service_v1_messages_proto protoreflect.FileDescriptor

const file_tiny_profile_service_v1_messages_proto_rawDesc = "" +
	"\n" +
	"&tiny-profile-service/v1/messages.proto\x12\x0fprofile.service\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x02\n" +
	"\aProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttime_zone\x18\x03 \x01(\tR\btimeZone\x12\x12\n" +
	"\x04lang\x18\x04 \x01(\tR\x04lang\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12\x18\n" +
	"\adeleted\x18\x06 \x01(\bR\adeleted\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9f\x04\n" +
	"\x06Person\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1e\n" +
	"\n" +
	"patronymic\x18\x05 \x01(\tR\n" +
	"patronymic\x127\n" +
	"\tbirth_day\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bbirthDay\x12\x1e\n" +
	"\n" +
	"department\x18\a \x01(\tR\n" +
	"department\x12\x1a\n" +
	"\bposition\x18\b \x01(\tR\bposition\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\n" +
	" \x01(\tR\tavatarUrl\x12\x16\n" +
	"\x06active\x18\v \x01(\bR\x06active\x12\x18\n" +
	"\adeleted\x18\f \x01(\bR\adeleted\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x124\n" +
	"\bprofiles\x18\x0f \x03(\v2\x18.profile.service.ProfileR\bprofilesB0Z.tiny-profile-service/grpc/tiny-profile-serviceb\beditionsp\xe8\a"

var file_tiny_profile_service_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tiny_profile_service_v1_messages_proto_goTypes = []any{
	(*Profile)(nil),               // 0: profile.service.Profile
	(*Person)(nil),                // 1: profile.service.Person
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_tiny_profile_service_v1_messages_proto_depIdxs = []int32{
	2, // 0: profile.service.Profile.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: profile.service.Profile.updated_at:type_name -> google.protobuf.Timestamp
	2, // 2: profile.service.Person.birth_day:type_name -> google.protobuf.Timestamp
	2, // 3: profile.service.Person.created_at:type_name -> google.protobuf.Timestamp
	2, // 4: profile.service.Person.updated_at:type_name -> google.protobuf.Timestamp
	0, // 5: profile.service.Person.profiles:type_name -> profile.service.Profile
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_tiny_profile_service_v1_messages_proto_init() }
func file_tiny_profile_service_v1_messages_proto_init() {
	if File_tiny_profile_service_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tiny_profile_service_v1_messages_proto_rawDesc), len(file_tiny_profile_service_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tiny_profile_service_v1_messages_proto_goTypes,
		DependencyIndexes: file_tiny_profile_service_v1_messages_proto_depIdxs,
		MessageInfos:      file_tiny_profile_service_v1_messages_proto_msgTypes,
	}.Build()
	File_tiny_profile_service_v1_messages_proto = out.File
	file_tiny_profile_service_v1_messages_proto_goTypes = nil
	file_tiny_profile_service_v1_messages_proto_depIdxs = nil
}
