// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.0
// source: tiny-profile-service/v1/person-service.proto

package tiny_profile_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_tiny_profile_service_v1_person_service_proto protoreflect.FileDescriptor

const file_tiny_profile_service_v1_person_service_proto_rawDesc = "" +
	"\n" +
	",tiny-profile-service/v1/person-service.proto\x12\x0fprofile.serviceB0Z.tiny-profile-service/grpc/tiny-profile-serviceb\beditionsp\xe8\a"

var file_tiny_profile_service_v1_person_service_proto_goTypes = []any{}
var file_tiny_profile_service_v1_person_service_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tiny_profile_service_v1_person_service_proto_init() }
func file_tiny_profile_service_v1_person_service_proto_init() {
	if File_tiny_profile_service_v1_person_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tiny_profile_service_v1_person_service_proto_rawDesc), len(file_tiny_profile_service_v1_person_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tiny_profile_service_v1_person_service_proto_goTypes,
		DependencyIndexes: file_tiny_profile_service_v1_person_service_proto_depIdxs,
	}.Build()
	File_tiny_profile_service_v1_person_service_proto = out.File
	file_tiny_profile_service_v1_person_service_proto_goTypes = nil
	file_tiny_profile_service_v1_person_service_proto_depIdxs = nil
}
