// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: tiny-profile-service/v1/profile-service.proto

package tiny_profile_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProfileService_Find_FullMethodName             = "/profile.service.ProfileService/Find"
	ProfileService_FindByID_FullMethodName         = "/profile.service.ProfileService/FindByID"
	ProfileService_FindByUserID_FullMethodName     = "/profile.service.ProfileService/FindByUserID"
	ProfileService_List_FullMethodName             = "/profile.service.ProfileService/List"
	ProfileService_ListAll_FullMethodName          = "/profile.service.ProfileService/ListAll"
	ProfileService_ListAllByPersons_FullMethodName = "/profile.service.ProfileService/ListAllByPersons"
	ProfileService_Save_FullMethodName             = "/profile.service.ProfileService/Save"
	ProfileService_Delete_FullMethodName           = "/profile.service.ProfileService/Delete"
)

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfileServiceClient interface {
	Find(ctx context.Context, in *ProfileFindRequest, opts ...grpc.CallOption) (*ProfileInstanceResponse, error)
	FindByID(ctx context.Context, in *ProfileFindByIDRequest, opts ...grpc.CallOption) (*ProfileInstanceResponse, error)
	FindByUserID(ctx context.Context, in *ProfileFindByUserIDRequest, opts ...grpc.CallOption) (*ProfileInstanceResponse, error)
	List(ctx context.Context, in *ProfileListRequest, opts ...grpc.CallOption) (*ProfileInstancesResponse, error)
	ListAll(ctx context.Context, in *ProfileListAllRequest, opts ...grpc.CallOption) (*ProfileInstancesResponse, error)
	ListAllByPersons(ctx context.Context, in *ProfileListAllByPersonsRequest, opts ...grpc.CallOption) (*ProfileListAllByPersonsResponse, error)
	Save(ctx context.Context, in *ProfileSaveRequest, opts ...grpc.CallOption) (*ProfileInstanceResponse, error)
	Delete(ctx context.Context, in *ProfileDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type profileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileServiceClient(cc grpc.ClientConnInterface) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) Find(ctx context.Context, in *ProfileFindRequest, opts ...grpc.CallOption) (*ProfileInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileInstanceResponse)
	err := c.cc.Invoke(ctx, ProfileService_Find_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) FindByID(ctx context.Context, in *ProfileFindByIDRequest, opts ...grpc.CallOption) (*ProfileInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileInstanceResponse)
	err := c.cc.Invoke(ctx, ProfileService_FindByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) FindByUserID(ctx context.Context, in *ProfileFindByUserIDRequest, opts ...grpc.CallOption) (*ProfileInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileInstanceResponse)
	err := c.cc.Invoke(ctx, ProfileService_FindByUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) List(ctx context.Context, in *ProfileListRequest, opts ...grpc.CallOption) (*ProfileInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileInstancesResponse)
	err := c.cc.Invoke(ctx, ProfileService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) ListAll(ctx context.Context, in *ProfileListAllRequest, opts ...grpc.CallOption) (*ProfileInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileInstancesResponse)
	err := c.cc.Invoke(ctx, ProfileService_ListAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) ListAllByPersons(ctx context.Context, in *ProfileListAllByPersonsRequest, opts ...grpc.CallOption) (*ProfileListAllByPersonsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileListAllByPersonsResponse)
	err := c.cc.Invoke(ctx, ProfileService_ListAllByPersons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Save(ctx context.Context, in *ProfileSaveRequest, opts ...grpc.CallOption) (*ProfileInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileInstanceResponse)
	err := c.cc.Invoke(ctx, ProfileService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Delete(ctx context.Context, in *ProfileDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProfileService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServiceServer is the server API for ProfileService service.
// All implementations must embed UnimplementedProfileServiceServer
// for forward compatibility.
type ProfileServiceServer interface {
	Find(context.Context, *ProfileFindRequest) (*ProfileInstanceResponse, error)
	FindByID(context.Context, *ProfileFindByIDRequest) (*ProfileInstanceResponse, error)
	FindByUserID(context.Context, *ProfileFindByUserIDRequest) (*ProfileInstanceResponse, error)
	List(context.Context, *ProfileListRequest) (*ProfileInstancesResponse, error)
	ListAll(context.Context, *ProfileListAllRequest) (*ProfileInstancesResponse, error)
	ListAllByPersons(context.Context, *ProfileListAllByPersonsRequest) (*ProfileListAllByPersonsResponse, error)
	Save(context.Context, *ProfileSaveRequest) (*ProfileInstanceResponse, error)
	Delete(context.Context, *ProfileDeleteRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedProfileServiceServer()
}

// UnimplementedProfileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProfileServiceServer struct{}

func (UnimplementedProfileServiceServer) Find(context.Context, *ProfileFindRequest) (*ProfileInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedProfileServiceServer) FindByID(context.Context, *ProfileFindByIDRequest) (*ProfileInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByID not implemented")
}
func (UnimplementedProfileServiceServer) FindByUserID(context.Context, *ProfileFindByUserIDRequest) (*ProfileInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindByUserID not implemented")
}
func (UnimplementedProfileServiceServer) List(context.Context, *ProfileListRequest) (*ProfileInstancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedProfileServiceServer) ListAll(context.Context, *ProfileListAllRequest) (*ProfileInstancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAll not implemented")
}
func (UnimplementedProfileServiceServer) ListAllByPersons(context.Context, *ProfileListAllByPersonsRequest) (*ProfileListAllByPersonsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAllByPersons not implemented")
}
func (UnimplementedProfileServiceServer) Save(context.Context, *ProfileSaveRequest) (*ProfileInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedProfileServiceServer) Delete(context.Context, *ProfileDeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedProfileServiceServer) mustEmbedUnimplementedProfileServiceServer() {}
func (UnimplementedProfileServiceServer) testEmbeddedByValue()                        {}

// UnsafeProfileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfileServiceServer will
// result in compilation errors.
type UnsafeProfileServiceServer interface {
	mustEmbedUnimplementedProfileServiceServer()
}

func RegisterProfileServiceServer(s grpc.ServiceRegistrar, srv ProfileServiceServer) {
	// If the following call panics, it indicates UnimplementedProfileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProfileService_ServiceDesc, srv)
}

func _ProfileService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileFindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_Find_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Find(ctx, req.(*ProfileFindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_FindByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileFindByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).FindByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_FindByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).FindByID(ctx, req.(*ProfileFindByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_FindByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileFindByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).FindByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_FindByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).FindByUserID(ctx, req.(*ProfileFindByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).List(ctx, req.(*ProfileListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_ListAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileListAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).ListAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_ListAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).ListAll(ctx, req.(*ProfileListAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_ListAllByPersons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileListAllByPersonsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).ListAllByPersons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_ListAllByPersons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).ListAllByPersons(ctx, req.(*ProfileListAllByPersonsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Save(ctx, req.(*ProfileSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Delete(ctx, req.(*ProfileDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfileService_ServiceDesc is the grpc.ServiceDesc for ProfileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "profile.service.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Find",
			Handler:    _ProfileService_Find_Handler,
		},
		{
			MethodName: "FindByID",
			Handler:    _ProfileService_FindByID_Handler,
		},
		{
			MethodName: "FindByUserID",
			Handler:    _ProfileService_FindByUserID_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ProfileService_List_Handler,
		},
		{
			MethodName: "ListAll",
			Handler:    _ProfileService_ListAll_Handler,
		},
		{
			MethodName: "ListAllByPersons",
			Handler:    _ProfileService_ListAllByPersons_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _ProfileService_Save_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ProfileService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tiny-profile-service/v1/profile-service.proto",
}
