// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.0
// source: tiny-profile-service/v1/profile-service.proto

package tiny_profile_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProfileFindRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PersonId    *string                `protobuf:"bytes,1,opt,name=person_id,json=personId"`
	xxx_hidden_Id          *string                `protobuf:"bytes,2,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProfileFindRequest) Reset() {
	*x = ProfileFindRequest{}
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileFindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileFindRequest) ProtoMessage() {}

func (x *ProfileFindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfileFindRequest) GetPersonId() string {
	if x != nil {
		if x.xxx_hidden_PersonId != nil {
			return *x.xxx_hidden_PersonId
		}
		return ""
	}
	return ""
}

func (x *ProfileFindRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *ProfileFindRequest) SetPersonId(v string) {
	x.xxx_hidden_PersonId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ProfileFindRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ProfileFindRequest) HasPersonId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ProfileFindRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ProfileFindRequest) ClearPersonId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PersonId = nil
}

func (x *ProfileFindRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Id = nil
}

type ProfileFindRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PersonId *string
	Id       *string
}

func (b0 ProfileFindRequest_builder) Build() *ProfileFindRequest {
	m0 := &ProfileFindRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PersonId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_PersonId = b.PersonId
	}
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type ProfileFindByIDRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProfileFindByIDRequest) Reset() {
	*x = ProfileFindByIDRequest{}
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileFindByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileFindByIDRequest) ProtoMessage() {}

func (x *ProfileFindByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfileFindByIDRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *ProfileFindByIDRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ProfileFindByIDRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ProfileFindByIDRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type ProfileFindByIDRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 ProfileFindByIDRequest_builder) Build() *ProfileFindByIDRequest {
	m0 := &ProfileFindByIDRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type ProfileFindByUserIDRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserId      *string                `protobuf:"bytes,1,opt,name=user_id,json=userId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProfileFindByUserIDRequest) Reset() {
	*x = ProfileFindByUserIDRequest{}
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileFindByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileFindByUserIDRequest) ProtoMessage() {}

func (x *ProfileFindByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfileFindByUserIDRequest) GetUserId() string {
	if x != nil {
		if x.xxx_hidden_UserId != nil {
			return *x.xxx_hidden_UserId
		}
		return ""
	}
	return ""
}

func (x *ProfileFindByUserIDRequest) SetUserId(v string) {
	x.xxx_hidden_UserId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ProfileFindByUserIDRequest) HasUserId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ProfileFindByUserIDRequest) ClearUserId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_UserId = nil
}

type ProfileFindByUserIDRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	UserId *string
}

func (b0 ProfileFindByUserIDRequest_builder) Build() *ProfileFindByUserIDRequest {
	m0 := &ProfileFindByUserIDRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.UserId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_UserId = b.UserId
	}
	return m0
}

type ProfileListRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PersonId    *string                `protobuf:"bytes,1,opt,name=person_id,json=personId"`
	xxx_hidden_Offset      uint32                 `protobuf:"varint,2,opt,name=offset"`
	xxx_hidden_Limit       uint32                 `protobuf:"varint,3,opt,name=limit"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProfileListRequest) Reset() {
	*x = ProfileListRequest{}
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileListRequest) ProtoMessage() {}

func (x *ProfileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfileListRequest) GetPersonId() string {
	if x != nil {
		if x.xxx_hidden_PersonId != nil {
			return *x.xxx_hidden_PersonId
		}
		return ""
	}
	return ""
}

func (x *ProfileListRequest) GetOffset() uint32 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *ProfileListRequest) GetLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ProfileListRequest) SetPersonId(v string) {
	x.xxx_hidden_PersonId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ProfileListRequest) SetOffset(v uint32) {
	x.xxx_hidden_Offset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ProfileListRequest) SetLimit(v uint32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ProfileListRequest) HasPersonId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ProfileListRequest) HasOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ProfileListRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ProfileListRequest) ClearPersonId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PersonId = nil
}

func (x *ProfileListRequest) ClearOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Offset = 0
}

func (x *ProfileListRequest) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Limit = 0
}

type ProfileListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PersonId *string
	Offset   *uint32
	Limit    *uint32
}

func (b0 ProfileListRequest_builder) Build() *ProfileListRequest {
	m0 := &ProfileListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PersonId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_PersonId = b.PersonId
	}
	if b.Offset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Offset = *b.Offset
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Limit = *b.Limit
	}
	return m0
}

type ProfileListAllRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PersonId    *string                `protobuf:"bytes,1,opt,name=person_id,json=personId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProfileListAllRequest) Reset() {
	*x = ProfileListAllRequest{}
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileListAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileListAllRequest) ProtoMessage() {}

func (x *ProfileListAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfileListAllRequest) GetPersonId() string {
	if x != nil {
		if x.xxx_hidden_PersonId != nil {
			return *x.xxx_hidden_PersonId
		}
		return ""
	}
	return ""
}

func (x *ProfileListAllRequest) SetPersonId(v string) {
	x.xxx_hidden_PersonId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ProfileListAllRequest) HasPersonId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ProfileListAllRequest) ClearPersonId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PersonId = nil
}

type ProfileListAllRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PersonId *string
}

func (b0 ProfileListAllRequest_builder) Build() *ProfileListAllRequest {
	m0 := &ProfileListAllRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PersonId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_PersonId = b.PersonId
	}
	return m0
}

type ProfileListAllByPersonsRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PersonId []string               `protobuf:"bytes,1,rep,name=person_id,json=personId"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProfileListAllByPersonsRequest) Reset() {
	*x = ProfileListAllByPersonsRequest{}
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileListAllByPersonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileListAllByPersonsRequest) ProtoMessage() {}

func (x *ProfileListAllByPersonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfileListAllByPersonsRequest) GetPersonId() []string {
	if x != nil {
		return x.xxx_hidden_PersonId
	}
	return nil
}

func (x *ProfileListAllByPersonsRequest) SetPersonId(v []string) {
	x.xxx_hidden_PersonId = v
}

type ProfileListAllByPersonsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PersonId []string
}

func (b0 ProfileListAllByPersonsRequest_builder) Build() *ProfileListAllByPersonsRequest {
	m0 := &ProfileListAllByPersonsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PersonId = b.PersonId
	return m0
}

type ProfileSaveRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PersonId    *string                `protobuf:"bytes,1,opt,name=person_id,json=personId"`
	xxx_hidden_Instance    *Profile               `protobuf:"bytes,2,opt,name=instance"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProfileSaveRequest) Reset() {
	*x = ProfileSaveRequest{}
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileSaveRequest) ProtoMessage() {}

func (x *ProfileSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfileSaveRequest) GetPersonId() string {
	if x != nil {
		if x.xxx_hidden_PersonId != nil {
			return *x.xxx_hidden_PersonId
		}
		return ""
	}
	return ""
}

func (x *ProfileSaveRequest) GetInstance() *Profile {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *ProfileSaveRequest) SetPersonId(v string) {
	x.xxx_hidden_PersonId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ProfileSaveRequest) SetInstance(v *Profile) {
	x.xxx_hidden_Instance = v
}

func (x *ProfileSaveRequest) HasPersonId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ProfileSaveRequest) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *ProfileSaveRequest) ClearPersonId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PersonId = nil
}

func (x *ProfileSaveRequest) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

type ProfileSaveRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PersonId *string
	Instance *Profile
}

func (b0 ProfileSaveRequest_builder) Build() *ProfileSaveRequest {
	m0 := &ProfileSaveRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PersonId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_PersonId = b.PersonId
	}
	x.xxx_hidden_Instance = b.Instance
	return m0
}

type ProfileDeleteRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PersonId    *string                `protobuf:"bytes,1,opt,name=person_id,json=personId"`
	xxx_hidden_Id          *string                `protobuf:"bytes,2,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProfileDeleteRequest) Reset() {
	*x = ProfileDeleteRequest{}
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileDeleteRequest) ProtoMessage() {}

func (x *ProfileDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfileDeleteRequest) GetPersonId() string {
	if x != nil {
		if x.xxx_hidden_PersonId != nil {
			return *x.xxx_hidden_PersonId
		}
		return ""
	}
	return ""
}

func (x *ProfileDeleteRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *ProfileDeleteRequest) SetPersonId(v string) {
	x.xxx_hidden_PersonId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ProfileDeleteRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ProfileDeleteRequest) HasPersonId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ProfileDeleteRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ProfileDeleteRequest) ClearPersonId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PersonId = nil
}

func (x *ProfileDeleteRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Id = nil
}

type ProfileDeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PersonId *string
	Id       *string
}

func (b0 ProfileDeleteRequest_builder) Build() *ProfileDeleteRequest {
	m0 := &ProfileDeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PersonId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_PersonId = b.PersonId
	}
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type ProfileInstanceResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Instance *Profile               `protobuf:"bytes,1,opt,name=instance"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProfileInstanceResponse) Reset() {
	*x = ProfileInstanceResponse{}
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileInstanceResponse) ProtoMessage() {}

func (x *ProfileInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfileInstanceResponse) GetInstance() *Profile {
	if x != nil {
		return x.xxx_hidden_Instance
	}
	return nil
}

func (x *ProfileInstanceResponse) SetInstance(v *Profile) {
	x.xxx_hidden_Instance = v
}

func (x *ProfileInstanceResponse) HasInstance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Instance != nil
}

func (x *ProfileInstanceResponse) ClearInstance() {
	x.xxx_hidden_Instance = nil
}

type ProfileInstanceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Instance *Profile
}

func (b0 ProfileInstanceResponse_builder) Build() *ProfileInstanceResponse {
	m0 := &ProfileInstanceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Instance = b.Instance
	return m0
}

type ProfileInstancesResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Offset      uint32                 `protobuf:"varint,1,opt,name=offset"`
	xxx_hidden_Limit       uint32                 `protobuf:"varint,2,opt,name=limit"`
	xxx_hidden_Instances   *[]*Profile            `protobuf:"bytes,3,rep,name=instances"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProfileInstancesResponse) Reset() {
	*x = ProfileInstancesResponse{}
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileInstancesResponse) ProtoMessage() {}

func (x *ProfileInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfileInstancesResponse) GetOffset() uint32 {
	if x != nil {
		return x.xxx_hidden_Offset
	}
	return 0
}

func (x *ProfileInstancesResponse) GetLimit() uint32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ProfileInstancesResponse) GetInstances() []*Profile {
	if x != nil {
		if x.xxx_hidden_Instances != nil {
			return *x.xxx_hidden_Instances
		}
	}
	return nil
}

func (x *ProfileInstancesResponse) SetOffset(v uint32) {
	x.xxx_hidden_Offset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ProfileInstancesResponse) SetLimit(v uint32) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ProfileInstancesResponse) SetInstances(v []*Profile) {
	x.xxx_hidden_Instances = &v
}

func (x *ProfileInstancesResponse) HasOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ProfileInstancesResponse) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ProfileInstancesResponse) ClearOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Offset = 0
}

func (x *ProfileInstancesResponse) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Limit = 0
}

type ProfileInstancesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Offset    *uint32
	Limit     *uint32
	Instances []*Profile
}

func (b0 ProfileInstancesResponse_builder) Build() *ProfileInstancesResponse {
	m0 := &ProfileInstancesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Offset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Offset = *b.Offset
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Limit = *b.Limit
	}
	x.xxx_hidden_Instances = &b.Instances
	return m0
}

type ProfilesByPerson struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PersonId    *string                `protobuf:"bytes,1,opt,name=person_id,json=personId"`
	xxx_hidden_Profiles    *[]*Profile            `protobuf:"bytes,2,rep,name=profiles"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProfilesByPerson) Reset() {
	*x = ProfilesByPerson{}
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilesByPerson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilesByPerson) ProtoMessage() {}

func (x *ProfilesByPerson) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfilesByPerson) GetPersonId() string {
	if x != nil {
		if x.xxx_hidden_PersonId != nil {
			return *x.xxx_hidden_PersonId
		}
		return ""
	}
	return ""
}

func (x *ProfilesByPerson) GetProfiles() []*Profile {
	if x != nil {
		if x.xxx_hidden_Profiles != nil {
			return *x.xxx_hidden_Profiles
		}
	}
	return nil
}

func (x *ProfilesByPerson) SetPersonId(v string) {
	x.xxx_hidden_PersonId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ProfilesByPerson) SetProfiles(v []*Profile) {
	x.xxx_hidden_Profiles = &v
}

func (x *ProfilesByPerson) HasPersonId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ProfilesByPerson) ClearPersonId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PersonId = nil
}

type ProfilesByPerson_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PersonId *string
	Profiles []*Profile
}

func (b0 ProfilesByPerson_builder) Build() *ProfilesByPerson {
	m0 := &ProfilesByPerson{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PersonId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_PersonId = b.PersonId
	}
	x.xxx_hidden_Profiles = &b.Profiles
	return m0
}

type ProfileListAllByPersonsResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ProfileBundle *[]*ProfilesByPerson   `protobuf:"bytes,1,rep,name=profileBundle"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ProfileListAllByPersonsResponse) Reset() {
	*x = ProfileListAllByPersonsResponse{}
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileListAllByPersonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileListAllByPersonsResponse) ProtoMessage() {}

func (x *ProfileListAllByPersonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tiny_profile_service_v1_profile_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfileListAllByPersonsResponse) GetProfileBundle() []*ProfilesByPerson {
	if x != nil {
		if x.xxx_hidden_ProfileBundle != nil {
			return *x.xxx_hidden_ProfileBundle
		}
	}
	return nil
}

func (x *ProfileListAllByPersonsResponse) SetProfileBundle(v []*ProfilesByPerson) {
	x.xxx_hidden_ProfileBundle = &v
}

type ProfileListAllByPersonsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ProfileBundle []*ProfilesByPerson
}

func (b0 ProfileListAllByPersonsResponse_builder) Build() *ProfileListAllByPersonsResponse {
	m0 := &ProfileListAllByPersonsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ProfileBundle = &b.ProfileBundle
	return m0
}

var File_tiny_profile_service_v1_profile_service_proto protoreflect.FileDescriptor

const file_tiny_profile_service_v1_profile_service_proto_rawDesc = "" +
	"\n" +
	"-tiny-profile-service/v1/profile-service.proto\x12\x0fprofile.service\x1a\x1bgoogle/protobuf/empty.proto\x1a&tiny-profile-service/v1/messages.proto\"A\n" +
	"\x12ProfileFindRequest\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"(\n" +
	"\x16ProfileFindByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x1aProfileFindByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"_\n" +
	"\x12ProfileListRequest\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"4\n" +
	"\x15ProfileListAllRequest\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\"=\n" +
	"\x1eProfileListAllByPersonsRequest\x12\x1b\n" +
	"\tperson_id\x18\x01 \x03(\tR\bpersonId\"g\n" +
	"\x12ProfileSaveRequest\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\x124\n" +
	"\binstance\x18\x02 \x01(\v2\x18.profile.service.ProfileR\binstance\"C\n" +
	"\x14ProfileDeleteRequest\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"O\n" +
	"\x17ProfileInstanceResponse\x124\n" +
	"\binstance\x18\x01 \x01(\v2\x18.profile.service.ProfileR\binstance\"\x80\x01\n" +
	"\x18ProfileInstancesResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x126\n" +
	"\tinstances\x18\x03 \x03(\v2\x18.profile.service.ProfileR\tinstances\"e\n" +
	"\x10ProfilesByPerson\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\x124\n" +
	"\bprofiles\x18\x02 \x03(\v2\x18.profile.service.ProfileR\bprofiles\"j\n" +
	"\x1fProfileListAllByPersonsResponse\x12G\n" +
	"\rprofileBundle\x18\x01 \x03(\v2!.profile.service.ProfilesByPersonR\rprofileBundle2\xfa\x05\n" +
	"\x0eProfileService\x12U\n" +
	"\x04Find\x12#.profile.service.ProfileFindRequest\x1a(.profile.service.ProfileInstanceResponse\x12]\n" +
	"\bFindByID\x12'.profile.service.ProfileFindByIDRequest\x1a(.profile.service.ProfileInstanceResponse\x12e\n" +
	"\fFindByUserID\x12+.profile.service.ProfileFindByUserIDRequest\x1a(.profile.service.ProfileInstanceResponse\x12V\n" +
	"\x04List\x12#.profile.service.ProfileListRequest\x1a).profile.service.ProfileInstancesResponse\x12\\\n" +
	"\aListAll\x12&.profile.service.ProfileListAllRequest\x1a).profile.service.ProfileInstancesResponse\x12u\n" +
	"\x10ListAllByPersons\x12/.profile.service.ProfileListAllByPersonsRequest\x1a0.profile.service.ProfileListAllByPersonsResponse\x12U\n" +
	"\x04Save\x12#.profile.service.ProfileSaveRequest\x1a(.profile.service.ProfileInstanceResponse\x12G\n" +
	"\x06Delete\x12%.profile.service.ProfileDeleteRequest\x1a\x16.google.protobuf.EmptyB0Z.tiny-profile-service/grpc/tiny-profile-serviceb\beditionsp\xe8\a"

var file_tiny_profile_service_v1_profile_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_tiny_profile_service_v1_profile_service_proto_goTypes = []any{
	(*ProfileFindRequest)(nil),              // 0: profile.service.ProfileFindRequest
	(*ProfileFindByIDRequest)(nil),          // 1: profile.service.ProfileFindByIDRequest
	(*ProfileFindByUserIDRequest)(nil),      // 2: profile.service.ProfileFindByUserIDRequest
	(*ProfileListRequest)(nil),              // 3: profile.service.ProfileListRequest
	(*ProfileListAllRequest)(nil),           // 4: profile.service.ProfileListAllRequest
	(*ProfileListAllByPersonsRequest)(nil),  // 5: profile.service.ProfileListAllByPersonsRequest
	(*ProfileSaveRequest)(nil),              // 6: profile.service.ProfileSaveRequest
	(*ProfileDeleteRequest)(nil),            // 7: profile.service.ProfileDeleteRequest
	(*ProfileInstanceResponse)(nil),         // 8: profile.service.ProfileInstanceResponse
	(*ProfileInstancesResponse)(nil),        // 9: profile.service.ProfileInstancesResponse
	(*ProfilesByPerson)(nil),                // 10: profile.service.ProfilesByPerson
	(*ProfileListAllByPersonsResponse)(nil), // 11: profile.service.ProfileListAllByPersonsResponse
	(*Profile)(nil),                         // 12: profile.service.Profile
	(*emptypb.Empty)(nil),                   // 13: google.protobuf.Empty
}
var file_tiny_profile_service_v1_profile_service_proto_depIdxs = []int32{
	12, // 0: profile.service.ProfileSaveRequest.instance:type_name -> profile.service.Profile
	12, // 1: profile.service.ProfileInstanceResponse.instance:type_name -> profile.service.Profile
	12, // 2: profile.service.ProfileInstancesResponse.instances:type_name -> profile.service.Profile
	12, // 3: profile.service.ProfilesByPerson.profiles:type_name -> profile.service.Profile
	10, // 4: profile.service.ProfileListAllByPersonsResponse.profileBundle:type_name -> profile.service.ProfilesByPerson
	0,  // 5: profile.service.ProfileService.Find:input_type -> profile.service.ProfileFindRequest
	1,  // 6: profile.service.ProfileService.FindByID:input_type -> profile.service.ProfileFindByIDRequest
	2,  // 7: profile.service.ProfileService.FindByUserID:input_type -> profile.service.ProfileFindByUserIDRequest
	3,  // 8: profile.service.ProfileService.List:input_type -> profile.service.ProfileListRequest
	4,  // 9: profile.service.ProfileService.ListAll:input_type -> profile.service.ProfileListAllRequest
	5,  // 10: profile.service.ProfileService.ListAllByPersons:input_type -> profile.service.ProfileListAllByPersonsRequest
	6,  // 11: profile.service.ProfileService.Save:input_type -> profile.service.ProfileSaveRequest
	7,  // 12: profile.service.ProfileService.Delete:input_type -> profile.service.ProfileDeleteRequest
	8,  // 13: profile.service.ProfileService.Find:output_type -> profile.service.ProfileInstanceResponse
	8,  // 14: profile.service.ProfileService.FindByID:output_type -> profile.service.ProfileInstanceResponse
	8,  // 15: profile.service.ProfileService.FindByUserID:output_type -> profile.service.ProfileInstanceResponse
	9,  // 16: profile.service.ProfileService.List:output_type -> profile.service.ProfileInstancesResponse
	9,  // 17: profile.service.ProfileService.ListAll:output_type -> profile.service.ProfileInstancesResponse
	11, // 18: profile.service.ProfileService.ListAllByPersons:output_type -> profile.service.ProfileListAllByPersonsResponse
	8,  // 19: profile.service.ProfileService.Save:output_type -> profile.service.ProfileInstanceResponse
	13, // 20: profile.service.ProfileService.Delete:output_type -> google.protobuf.Empty
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_tiny_profile_service_v1_profile_service_proto_init() }
func file_tiny_profile_service_v1_profile_service_proto_init() {
	if File_tiny_profile_service_v1_profile_service_proto != nil {
		return
	}
	file_tiny_profile_service_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tiny_profile_service_v1_profile_service_proto_rawDesc), len(file_tiny_profile_service_v1_profile_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tiny_profile_service_v1_profile_service_proto_goTypes,
		DependencyIndexes: file_tiny_profile_service_v1_profile_service_proto_depIdxs,
		MessageInfos:      file_tiny_profile_service_v1_profile_service_proto_msgTypes,
	}.Build()
	File_tiny_profile_service_v1_profile_service_proto = out.File
	file_tiny_profile_service_v1_profile_service_proto_goTypes = nil
	file_tiny_profile_service_v1_profile_service_proto_depIdxs = nil
}
